language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: bhtKs2K6LaYcXMDIoe+1tyAoTrCfzxOSeop2El5RBySqBueV6CdyapSRsgdcYmdAqpDoOWi9FlweQ8ky8EhoJnpdLmjKCN/7yEtL9fVPVdquoUNleL/UNw+h8sqk0+S6uYW8Zszpf+VG+Kcf9Omwxzy8KloGHTEdFWwhKbwYr9ED8q3VBTuXTf4+FmDmoFhw1iw911YL2lajNZ64Af3l4P/IlxZSOsvWfN0Q0WiGkDwdpkAOWe+sHFPmP1ANmwrFujxuJbvh34YVjAgAI8JGtHUUmE3b95KhP7MmKGcVcUdgfvUQ855ABVZJuoHxL9kz5jjmxWEP0aqjzdDNXj6/3WvW0o7pjbazZr9FTZaK5gWkT+jLt11Anhr9i2YGAatsuYA+JhwiMvzux31mYuUlYKS1GT8aX5v9M+PjGLrA9jdWBUtqzPe7Oaj4dy3fwIV15G62IBcIj4+AUFsoIsrMocqjMhAOxfSCn1CvDUz4vHzbCcAScQcETIK1HlR8l/+quKCkOAVpoFScrmp0wdMYKHSQBJ5zId0cL+av0njeTS0pRAjAZbMvkGs5vn+I4maz+P3cqx5g9nrYcVE9pS/10IptOt4539kwjqsXO/R6un+VgbAQSP33emnPEm1Uqntib3x4X4tGq13sFItH51y7vI42Sv8e57SVQxlVQUk4w0Y=
  app: desolate-beach-86485
  skip_cleanup: true